Update _config.yml
Updated to my URL and same host IP
Error: I updated all the gem bundles, but it now would just stall while loading instead of crashing out.